name: CI/CD - Deploy to Homelab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop old deployment
        run: |
          docker compose down || true

      - name: Build updated images
        working-directory: ${{ github.workspace }}
        run: docker compose -f docker-compose.yml build --no-cache

      - name: Start updated stack
        working-directory: ${{ github.workspace }}
        run: docker compose -f docker-compose.yml up -d


      - name: Show running containers
        run: docker ps
